In [1]:
range(4)

range(0, 4)

In [2]:
list(range(4))

[0, 1, 2, 3]

In [1]:
import numpy as np
import matplotlib.pyplot as plt

data = np.random.randint(3, 7, (10, 1, 1, 80))
newdata = np.squeeze(data) # Shape is now: (10, 80)
plt.plot(newdata) # plotting by columns
plt.show()

<Figure size 640x480 with 1 Axes>

In [13]:

x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [15]:
A = 5 * x
A

array([[ 5, 10],
       [15, 20]])

In [3]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
y = np.transpose([x])
y

array([[1],
       [2],
       [3]])

In [6]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [16]:
np.shape(x)

(3,)

In [10]:
y*x

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [12]:
a=np.array([2,3])
a

array([2, 3])

In [14]:
b=np.transpose([a])
b

array([[2],
       [3]])

In [17]:
x * b

array([[2, 4, 6],
       [3, 6, 9]])

In [3]:
a = [float(x) for x in input().split()]

4.7 9.9 5.5


In [4]:
a

[4.7, 9.9, 5.5]

In [1]:
import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

A = 10 
C = 3   
k = 1 
B = 2 

tao = A / C

def f(C_A):
    z = C_A - B + k * C_A * tao
    return z

ssconc, = fsolve(f, 2.0, full_output=0)
B0 = 0
t = np.linspace(0, 20)

def g(C_A, t):
    dCAdt = (B - C_A) / tao - k * C_A
    return dCAdt

ans = odeint(g, B0, t)

def h(C_A):
    y = C_A - C_Af + k * C_A * tao
    return y

ssconc, = fsolve(h, 2.0, full_output=0)

Creq = 0.75 * ssconc

def k(C_A, t):
    z = ans - Creq
    return z

ans, = fsolve(k, 0, t)
print(ans)


NameError: name 'fsolve' is not defined